(define (problem flare-problem)
  (:domain flare-domain)
  (:objects
    Microsoft-Windows-12-Server firewall-vpn internal-network plc-allen-brdley-controllogix plc-yokogawa-stardom plc-Allen-Bradley-MicroLogix-1100 plc-Siemens-S7-1200 plc-Siemens-S7-300-or-400 plc-Schneider-Electric-Modicon-M580 plc-Mitsubishi-MELSEC-Q-Series plc-Schneider-Electric-Modicon-M221 - node
  )
  (:init
    (has-compromised-customer-pc)
    (has-compromised-engineering-workstations)
    (has-vulnerability-CVE-2019-0575 Microsoft-Windows-12-Server)
    (has-done-remote-code-execution Microsoft-Windows-12-Server)
    (has-fault-pipe-not-drained)
    (has-vulnerability-CVE-2017-9312 plc-allen-brdley-controllogix)
    (has-vulnerability-CVE-2018-10594 plc-yokogawa-stardom)
    (has-vulnerability-CVE-2017-12089 plc-Allen-Bradley-MicroLogix-1100)
    (has-vulnerability-CVE-2018-13810 plc-Siemens-S7-1200)
    (has-vulnerability-CVE-2017-12741 plc-Siemens-S7-1200)
    (has-vulnerability-CVE-2017-12741 plc-Siemens-S7-300-or-400)
    (has-vulnerability-CVE-2016-8673 plc-Siemens-S7-300-or-400)
    (has-vulnerability-CVE-2019-6815 plc-Schneider-Electric-Modicon-M580)
    (has-vulnerability-CVE-2017-9638 plc-Mitsubishi-MELSEC-Q-Series)
    (has-vulnerability-CVE-2017-6034 plc-Schneider-Electric-Modicon-M221)
    (has-vulnerability-CVE-2017-6032 plc-Schneider-Electric-Modicon-M221)
    (has-connected Microsoft-Windows-12-Server internal-network)
    (has-connected firewall-vpn internal-network)
    (has-connected internal-network plc-allen-brdley-controllogix)
    (has-connected internal-network plc-yokogawa-stardom)
    (has-connected internal-network plc-Allen-Bradley-MicroLogix-1100)
    (has-connected internal-network plc-Siemens-S7-1200)
    (has-connected internal-network plc-Siemens-S7-300-or-400)
    (has-connected internal-network plc-Schneider-Electric-Modicon-M580)
    (has-connected internal-network plc-Mitsubishi-MELSEC-Q-Series)
    (has-connected internal-network plc-Schneider-Electric-Modicon-M221)
  )
  (:goal (and
     (has-fault-flare-flameout)        
  )
)
)